// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhMXB33G2i1nsRAyuEd--MF2jUB70sJCc',
    appId: '1:465232760174:web:9dfe898e61de0db255057f',
    messagingSenderId: '465232760174',
    projectId: 'task-9994d',
    authDomain: 'task-9994d.firebaseapp.com',
    storageBucket: 'task-9994d.firebasestorage.app',
    measurementId: 'G-QH8YZ3GWDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgMKIx0pA_RrbjodI5Z4m1InbO-xYc_rc',
    appId: '1:465232760174:android:640d2331fc4e628655057f',
    messagingSenderId: '465232760174',
    projectId: 'task-9994d',
    storageBucket: 'task-9994d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_tIKqn3gu35vGzQK2CtBJsd6W_lKN6IU',
    appId: '1:465232760174:ios:d8a6ecc63d7289f755057f',
    messagingSenderId: '465232760174',
    projectId: 'task-9994d',
    storageBucket: 'task-9994d.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

}